import Head from 'next/head';
import css from '../styles/Home.module.css';
import { HiShoppingCart } from 'react-icons/hi';
import { AiOutlineUser, AiOutlineSearch, AiFillStar } from 'react-icons/ai';
import shoe from '../assets/s.jpg';
import Image from 'next/image';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={css.main}>
        <header className={css.header}>
          <nav className={css.nav}>
            <label>Logo</label>
            <nav className={css.flex}>
              <div className={css.list}>
                <li className={css.item}>Home</li>
                <li className={css.item}>Home</li>
                <li className={css.item}>Home</li>
                <li className={css.item}>Home</li>
                <li className={css.item}>Home</li>
              </div>
              <ul className={css.icon}>
                <AiOutlineSearch className={css.item} />
                <AiOutlineUser className={css.item} />
                <HiShoppingCart className={css.list} />
              </ul>
            </nav>
          </nav>
        </header>

        <section className={css.section}>
          <div className={css.text}>
            <h1>#1 Best Shopping Center</h1>
            <p>lorem ipsumsum d orem ipsum d orem ipsum d</p>
            <p>lorem ipsumsum d orem ipsum d orem ipsum d</p>
            <p>lorem ipsumsum d orem ipsum d orem ipsum d</p>
            <button className={css.btn}>SHOP NOW</button>
          </div>
        </section>

        <section className={css.category}>
          <div className={css.card}>
            <p className={css.categoryText}>Women's</p>
          </div>
          <div className={css.card}>
            <p className={css.categoryText}>Women's</p>
          </div>
          <div className={css.card}>
            <p className={css.categoryText}>Women's</p>
          </div>
          <div className={css.card}>
            <p className={css.categoryText}>Women's</p>
          </div>
          <div className={css.card}>
            <p className={css.categoryText}>Women's</p>
          </div>
          <div className={css.card}>
            <p className={css.categoryText}>Women's</p>
          </div>
          <div className={css.card}>
            <p className={css.categoryText}>Women's</p>
          </div>
          <div className={css.card}>
            <p className={css.categoryText}>Women's</p>
          </div>
        </section>

        <section className={css.product}>
          <div className={css.productCategory}>
            <p className={css.productLane}>SHOES</p>
            <div className={css.productCardContainer}>
              <div className={css.productCard}>
                <Image
                  className={css.productImage}
                  width={300}
                  height={200}
                  src={shoe}
                  alt='shoe'
                />
                <div className={css.desc}>
                  <span className={css.name}>Cotton Sneakers</span>
                  <span>
                    {[
                      <AiFillStar className={css.star} />,
                      <AiFillStar className={css.star} />,
                      <AiFillStar className={css.star} />,
                      <AiFillStar className={css.star} />,
                    ]}
                  </span>
                  <span className={css.price}>$89.00</span>
                </div>
              </div>
            </div>
          </div>
          <div className={css.productCategory}>
            <p className={css.productLane}>WATCHES</p>
            <div className={css.productCardContainer}>
              <div className={css.productCard}>
                <Image
                  className={css.productImage}
                  width={300}
                  height={200}
                  src={shoe}
                  alt='shoe'
                />
                <div className={css.desc}>
                  <span className={css.name}>Cotton Sneakers</span>
                  <span>
                    {[
                      <AiFillStar className={css.star} />,
                      <AiFillStar className={css.star} />,
                      <AiFillStar className={css.star} />,
                      <AiFillStar className={css.star} />,
                    ]}
                  </span>
                  <span className={css.price}>$89.00</span>
                </div>
              </div>
            </div>
          </div>
          <div className={css.productCategory}>
            <p className={css.productLane}>GLASSES</p>
            <div className={css.productCardContainer}>
              <div className={css.productCard}>
                <Image
                  className={css.productImage}
                  width={300}
                  height={200}
                  src={shoe}
                  alt='shoe'
                />
                <div className={css.desc}>
                  <span className={css.name}>Cotton Sneakers</span>
                  <span>
                    {[
                      <AiFillStar className={css.star} />,
                      <AiFillStar className={css.star} />,
                      <AiFillStar className={css.star} />,
                      <AiFillStar className={css.star} />,
                    ]}
                  </span>
                  <span className={css.price}>$89.00</span>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
