import React, { useState } from 'react';
import { client } from '../library/client';
import { SearchProductAndCategories } from '../components';
import Head from 'next/head';

const search = ({ result }) => {
  const [selectedValue, setSelectedValue] = useState('name');
  return (
    <div>
      <Head>
        <title>Search | JestinaCommerce</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <SearchProductAndCategories
          data={result}
          selectedValue={selectedValue}
          setSelectedValue={setSelectedValue}
        />
      </div>
    </div>
  );
};

export const getStaticProps = async () => {
  const query = `*[_type == 'product']{
    name,
  slug,
  image,
  new_price,
  old_price,
}`;

  const queryCategory = `*[_type == 'category']`;

  const result = await client.fetch(query);
  const categories = await client.fetch(queryCategory);

  return {
    props: {
      result,
      categories,
    },
  };
};

export default search;
