import React, { useState } from 'react';
import css from '../styles/success.module.css';
import Link from 'next/link';
import Head from 'next/head';
import { MdOutlineAlternateEmail, MdSend } from 'react-icons/md';

const success = () => {
  const [email, setEmail] = useState('');

  const handleEmailSubmission = () => {};
  return (
    <div className={css.container}>
      <Head>
        <title>Success Page | DempiCommerce</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section className={css.thankyou}>
        <img src='/loading.gif' alt='success page' className={css.image} />
        <h1>THANK TOU FOR YOUR PURCHASE</h1>
        <p>
          Your order ID number is: <strong>00000021334</strong>.
        </p>
        <p>
          We'll email you an order confirmation with details and tracking info.
        </p>
        <Link href='/'>
          <button type='button' className={css.btn}>
            Continue Shopping
          </button>
        </Link>
      </section>

      <section className={css.productOnWay}>
        <img src='/success.gif' alt='product on way' className={css.image} />
        <div>
          <h3>Relax, Your items are on their way</h3>
          <p className={css.text}>
            Your shopping items will be reaching you in only 1-2 business days,
            with no damage.
          </p>
        </div>
      </section>

      <section className={css.subscribe}>
        <div className={css.email}>
          <img src='/email.png' alt='' />
          <p>
            Subscribe to receive important product updates and special discount
            in your email directly
          </p>
        </div>
        <div className={css.inputContainer}>
          <div className={css.inputAndIcon}>
            <input
              type='text'
              placeholder='example@company.com'
              className={css.input}
            />
            <MdOutlineAlternateEmail className={css.icon} />
          </div>
          <button
            type='submit'
            onClick={handleEmailSubmission}
            className={css.sendButton}
          >
            <MdSend />
          </button>
        </div>
      </section>
    </div>
  );
};

export default success;
